// Copyright 2018 Silicon Laboratories, Inc.
//
//

/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef __GATT_DB_H
#define __GATT_DB_H

#include "bg_gattdb_def.h"

extern const struct bg_gattdb_def bg_gattdb_data;

#define gattdb_service_changed_char             3
#define gattdb_device_name                      7
#define gattdb_ota_control                     19
#define gattdb_temperature_measurement         22
#define gattdb_temperature_type                25
#define gattdb_intermediate_temperature         27
#define gattdb_measurement_interval            30
#define gattdb_valid_range                     32
#define gattdb_tx_power_level                  35

#endif
